### PR TITLE
feat: Compatibility with AzureRM 4

### PR DESCRIPTION
**Pull request by jlauert**
COMPATIBILITY: audit_retention_period is no longer used because retention policy handling changed in Azure

### CODE REVIEW

**Comment by dploeger** [comment]
I've seen this as well in another project. The retention needs to be configured using a blob storage retention setting.

@timdeluxe What do you say? Can we skip custom retention settings for the time being to be compatible with AzureRM4?

**Comment by timdeluxe** [comment]
Well, retention was a requirement in a project (don't ask me which and we shouldn't give details here on github). The affected project should use the module versioned, so if that project stays at a lower version number of this module and also at AzureRM < 4, they should be fine.

Question is, if those projects need to update to newer provider or another new project has rentention requirements, how is that then configured? Imho that "option" needs to be included in this module and that is why i don't want to approve yet...

**Comment by dploeger** [comment]
@timdeluxe It is documented here: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy?tabs=portal

You basically configure the retention based on the blobs the diagnostics generate. It's not an easy task and I didn't want to force @jlauert to implement it with him being so nice to provide the PR to make it work with AzureRM4.

We could implement it if the requirement comes again.

**Comment by timdeluxe** [comment]
Okay, my eyes were blind yesterday. This deals about audit. Somewhere in my head i had retention regarding deleted keyvault entries.
The customer requiring that audit stuff has moved to Pulumi anyway, if i am not mistaken and the other one which i had in mind is not using audit.
So i am fine with this change.

**Review by timdeluxe — APPROVED** [review]
Thanks 🎁

**Pull request merged**
